# Generated by Django 4.2 on 2023-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0003_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
